title: Personal Writing
author:
  name: Kevin Today
  email: ""
description: |
  A collection of my personal writing
theme: minima

# Minima config
header_pages:
  # We use a nonexistent page here so that we don't have any header pages
  - Nonexistent

minima:
  social_links:
    instagram: kevinjtoday
    github: mieubrisse
