version: 2.1

jobs:
  validate:
    docker:
      # Needed for `npm install` down below
      - image: ghcr.io/tcort/markdown-link-check:stable
    resource_class: small
    steps:
      - checkout

      - run:
          name: Check links in Markdown docs
          command: |
            bash .circleci/check-markdown-links.sh

workflows:
  build:
    jobs:
      - validate:
          filters:
            branches:
              ignore: master
